### ISSUE TITLE
HYPO2000 and NLLOC

### ISSUE THREAD

**Issue by shicks-seismo** [megies/obspyck#41]
What is the default path for obspyck to find these plug-ins?

I was looking through past questions and these talked about setting --pluginpath, but this option doesn't seem to be there any more ...

Thanks

**Comment by megies** [comment]
There's been a lot of changes in options/settings in obspyck recently. Many things are now handled via a config file. When you first start obspyck and no config file is specified or found in the usual spots, a new config file is created in your home directory. Also see the `example.cfg` in the repo. The config file isn't documented, unfortunately, because every day just has 24 hours, unfortunately. But it's kind of self-documenting..
