### ISSUE TITLE
Port to Qt5?

### ISSUE THREAD

**Issue by thelenwes** [megies/obspyck#87]
Because Anaconda no longer supports qt4 on macosx, the installation of obspyck fails.  Are there any tips on how to get qt4 in an alternative way that will play nice within a conda environment?

**Comment by megies** [comment]
I may not have time to look into transitioning to Qt5 in the near future, sorry. Necessary changes in source code might be trivial or not, hard to tell. Let me know if you try to adapt the source code and how it goes.

**Comment by megies** [comment]
Also, might be worth to switch to PySide 2 instead

**Comment by fontiela** [comment]
There are a new version with support to  qt5.x.x?

**Comment by megies** [comment]
Not that I know of

**Comment by megies** [comment]
We had just had a similar problem on Windows. It turned out you can run obspyck on windows by installing qt4 from a non-default conda-forge channel/label.. there is one test build of qt4 for osx, maybe you could try that one @fontiela 

https://anaconda.org/conda-forge/qt/4.8.7/download/osx-64/qt-4.8.7-7.tar.bz2

maybe it works, it's try in a new environment though, so you don't crash your existing envs
`conda install -c conda-forge/label/cf201901 qt=4`

**Comment by fontiela** [comment]
That is a great new.
During the weekend I will try and I will let you know if I install with success. 

Yours,
João Fontiela

*********************
*********************
João Fontiela
skype: fontiela
email: fontiela@gmail.com
mobile phone +351 917 862 830

**Comment by savardge** [comment]
@fontiela Hello, did you ever manage to make the installation work with your Mac? 
I tried installing qt4 and pyqt4 from .tar.gz archives but then running obspyck produced segmentation fault. Let me know if you ever managed to create a condo environment that worked on MacOS (I run 10.15).

**Comment by megies** [comment]
@jwassermann is running it on a Mac, maybe he can share a `conda list` on his environment

**Comment by megies** [comment]
@thelenwes @fontiela @savardge the move to Qt5 and Python3 is under way, see #96
